# Generated by Django 3.2.3 on 2021-05-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('cash', models.CharField(max_length=200)),
                ('market', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('detail', models.TextField()),
            ],
        ),
    ]
