# Generated by Django 3.2.3 on 2021-06-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_currentportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('ordertime', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TickerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
            ],
        ),
    ]
