# Generated by Django 3.2.3 on 2021-06-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_currentorders_tickerset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('ordertime', models.DateTimeField()),
                ('ticker', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='currentorders',
            name='ordertime',
            field=models.DateTimeField(),
        ),
    ]
