# Generated by Django 3.2.3 on 2021-07-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210625_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorders',
            name='condition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
