# Generated by Django 3.2.3 on 2021-07-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_pendingorders_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorders',
            name='quantity',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
